org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true

android.useAndroidX=true

GROUP=io.github.ch000se
VERSION_NAME=0.1.0
POM_INCEPTION_YEAR=2026

POM_DESCRIPTION=KSP annotation processor that generates data class mappers
POM_URL=https://github.com/ch000se/auto-map

POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://github.com/ch000se/auto-map/blob/main/LICENSE

POM_SCM_URL=https://github.com/ch000se/auto-map
POM_SCM_CONNECTION=scm:git:git://github.com/ch000se/auto-map.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/ch000se/auto-map.git

POM_DEVELOPER_ID=ch000se
POM_DEVELOPER_NAME=Sviatoslav Chaikivskyi
POM_DEVELOPER_EMAIL=svyatikchaykivskiy@gmail.com