package io.github.ch000se.automap.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import io.github.ch000se.automap.compiler.generation.RegisteredMapper
import kotlin.math.absoluteValue

private const val GENERATED_METADATA_PACKAGE = "io.github.ch000se.automap.generated"
private const val GENERATED_METADATA_PATH = "io/github/ch000se/automap/generated/AutoMapGeneratedMetadata"

/**
 * Emits compile-time mapper metadata used by downstream modules.
 *
 * Two artifacts are written:
 *
 * - `META-INF/automap/mappings`, a resource file useful for packaging and inspection.
 * - `io.github.ch000se.automap.generated.AutoMapGeneratedMetadata`, a Kotlin source file carrying
 *   `@AutoMapGeneratedMapping` annotations that downstream KSP runs can discover through
 *   `Resolver.getDeclarationsFromPackage`.
 *
 * Both outputs are aggregating because they list every mapper generated in the current module.
 */
internal class MapperMetadataEmitter(
    private val codeGenerator: CodeGenerator,
) {
    /**
     * Writes metadata for [mappings]. Does nothing when the current module has no generated
     * mappings.
     */
    fun write(mappings: List<RegisteredMapper>, jobs: List<MappingJob>) {
        if (mappings.isEmpty()) return
        val sources = jobs.mapNotNull { it.annotatedSymbol.containingFile }.distinct().toTypedArray()
        val dependencies = Dependencies(aggregating = true, sources = sources)
        codeGenerator.createNewFileByPath(
            dependencies = dependencies,
            path = AUTOMAP_METADATA_PATH,
            extensionName = "",
        ).bufferedWriter().use { writer ->
            writer.appendLine("# Generated by AutoMap. Do not edit.")
            mappings.sortedWith(compareBy<RegisteredMapper> { it.sourceFqn }.thenBy { it.targetFqn })
                .forEach { writer.appendLine(it.toMetadataLine()) }
        }
        codeGenerator.createNewFileByPath(
            dependencies = dependencies,
            path = GENERATED_METADATA_PATH,
            extensionName = "kt",
        ).bufferedWriter().use { writer ->
            writer.appendLine("package $GENERATED_METADATA_PACKAGE")
            writer.appendLine()
            writer.appendLine("import io.github.ch000se.automap.annotations.AutoMapGeneratedMapping")
            writer.appendLine()
            writer.appendLine("// Generated by AutoMap. Do not edit.")
            mappings.sortedWith(compareBy<RegisteredMapper> { it.sourceFqn }.thenBy { it.targetFqn })
                .forEach { mapping ->
                    writer.appendLine("@AutoMapGeneratedMapping(")
                    writer.appendLine("    sourceFqn = \"${mapping.sourceFqn}\",")
                    writer.appendLine("    targetFqn = \"${mapping.targetFqn}\",")
                    writer.appendLine("    functionFqn = \"${mapping.functionFqn}\",")
                    writer.appendLine("    functionName = \"${mapping.functionName}\",")
                    writer.appendLine("    sourcePackage = \"${mapping.sourcePackage}\",")
                    writer.appendLine("    targetPackage = \"${mapping.targetPackage}\",")
                    writer.appendLine(")")
                    writer.appendLine("internal object ${mapping.metadataObjectName()}")
                    writer.appendLine()
                }
        }
    }

    private fun RegisteredMapper.metadataObjectName(): String {
        val hash = listOf(sourceFqn, targetFqn, functionFqn).joinToString("|").hashCode().absoluteValue
        val source = sourceFqn.substringAfterLast('.').sanitizeIdentifier()
        val target = targetFqn.substringAfterLast('.').sanitizeIdentifier()
        return "AutoMap_${source}_To_${target}_$hash"
    }

    private fun String.sanitizeIdentifier(): String =
        map { if (it.isLetterOrDigit()) it else '_' }
            .joinToString("")
            .let { if (it.firstOrNull()?.isDigit() == true) "_$it" else it }
}
