package io.github.ch000se.automap.compiler.generation

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Writes a resolved [MapperFile] to KSP using KotlinPoet.
 *
 * This class owns file-level output concerns only: package, file name, generated file comment,
 * dependency tracking, and handoff to [CodeGenerator]. Function bodies are delegated to
 * [MapperFunctionRenderer].
 *
 * @property codeGenerator KSP file writer used for generated Kotlin sources.
 * @property dependencyFiles Source files that affect the generated mapper output.
 * @property functionRenderer Renderer used to convert mapper metadata into KotlinPoet functions.
 */
internal class MapperEmitter(
    private val codeGenerator: CodeGenerator,
    private val functionRenderer: MapperFunctionRenderer = MapperFunctionRenderer(),
) {

    /**
     * Emits [file] as a generated Kotlin source file.
     *
     * Mapper files are isolating: each file depends on the source and target declarations used for
     * that mapper. The registry documentation file is emitted separately as aggregating.
     */
    @Suppress("SpreadOperator")
    fun write(file: MapperFile) {
        val fileSpec = FileSpec.builder(file.packageName, file.fileName)
            .addFileComment("Generated by AutoMap. Do not edit.")
            .apply {
                file.imports
                    .filterNot { it.packageName == file.packageName || it.packageName.isBlank() }
                    .distinct()
                    .forEach { addImport(it.packageName, it.name) }
                file.functions
                    .flatMap(functionRenderer::render)
                    .forEach(::addFunction)
            }
            .build()
        fileSpec.writeTo(codeGenerator, Dependencies(aggregating = false, *file.dependencyFiles.toTypedArray()))
    }
}
